name: CI model to dockerhub

# Trigger
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

# Actions
jobs:
  build_docker_image:
    runs-on: ubuntu-latest

    steps:
    - name: Check the repo
      uses: actions/checkout@v2

    - name: List files in repository
      run: ls -R
      
    - name: Login to dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build docker image
      run: docker build -t josiprz/predict-delivery-eta:v1 .

    - name: Docker push to Dockerhub
      run: docker push josiprz/predict-delivery-eta:v1

    - name : Login into Server
      run: echo '${{ secrets.DOCKER_PASSWORD }}' | docker login -u '${{ secrets.DOCKER_USERNAME }}' --password-stdin

    - name : Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          docker login
          if docker ps --all | grep predict-delivery-eta; then
            docker stop predict-delivery-eta
            docker rm predict-delivery-eta
          fi 
          
          docker pull ${{ secrets.EC2_USERNAME }}/predict-delivery-eta:latest
          docker run -d --name predict-delivery-eta -p 8000:8000 ${{ secrets.EC2_USERNAME }}/predict-delivery-eta:latest



